/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author syndu
 */
public class AddPlayerNames extends javax.swing.JFrame {

    public ArrayList<String> playerIds;
    /**
     * Creates new form AddPlayerNames
     */
    public AddPlayerNames() {
        initComponents();
        playerIds = new ArrayList<>();
    }

    public String[] getPids() {
        String[] pids = playerIds.toArray(new String[playerIds.size()]);
        return pids;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        pidOneLabel = new javax.swing.JLabel();
        pidTwoLabel = new javax.swing.JLabel();
        pidThreeLabel = new javax.swing.JLabel();
        pidFourLabel = new javax.swing.JLabel();
        doneButton4 = new javax.swing.JButton();
        doneButton3 = new javax.swing.JButton();
        doneButton2 = new javax.swing.JButton();
        doneButton1 = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        pidTextBox = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        guideButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Додавання гравців");
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(616, 639));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\button_add.png")); // NOI18N
        saveButton.setContentAreaFilled(false);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 282, 36, 36));

        pidOneLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pidOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pidOneLabel.setAlignmentX(0.5F);
        getContentPane().add(pidOneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 90, 40));

        pidTwoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pidTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pidTwoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, 40));

        pidThreeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pidThreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pidThreeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 90, 40));

        pidFourLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pidFourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pidFourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 90, 40));

        doneButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\слоти.png")); // NOI18N
        doneButton4.setContentAreaFilled(false);
        doneButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 390, 97, 48));

        doneButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\слоти.png")); // NOI18N
        doneButton3.setContentAreaFilled(false);
        doneButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 390, 97, 48));

        doneButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\слоти.png")); // NOI18N
        doneButton2.setContentAreaFilled(false);
        doneButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 330, 97, 48));

        doneButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\слоти.png")); // NOI18N
        doneButton1.setContentAreaFilled(false);
        doneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 330, 97, 48));

        doneButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\player_vs_player.png")); // NOI18N
        doneButton.setContentAreaFilled(false);
        doneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneButtonMouseExited(evt);
            }
        });
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 452, 97, 48));

        pidTextBox.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pidTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pidTextBox.setBorder(null);
        getContentPane().add(pidTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 284, 182, 30));

        returnButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\button_back.png")); // NOI18N
        returnButton.setContentAreaFilled(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnButtonMouseExited(evt);
            }
        });
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 404, 51, 51));

        guideButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\button_guid.png")); // NOI18N
        guideButton.setContentAreaFilled(false);
        guideButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guideButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guideButtonMouseExited(evt);
            }
        });
        guideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideButtonActionPerformed(evt);
            }
        });
        getContentPane().add(guideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 464, 51, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\вікно_додавання_учасників_з_кнопками_з_виїмками.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(pidTextBox.getText().isEmpty()) {
        JLabel message = new JLabel("Будь-ласка, введіть ім'я");
        message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
        JOptionPane.showMessageDialog(null, message);
    }
        else if(pidOneLabel.getText() .equals(pidTextBox.getText()) || pidTwoLabel.getText() .equals(pidTextBox.getText()) || pidThreeLabel.getText() .equals(pidTextBox.getText()) || pidFourLabel.getText() .equals(pidTextBox.getText()))
        {
            JLabel message = new JLabel("Імена гравців повинні відрізнятись!");
        message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
        JOptionPane.showMessageDialog(null, message);
        }
        else {
            String name = pidTextBox.getText().trim();
            playerIds.add(name);
            
            SoundManager.playSound("C:\\Users\\syndu\\Downloads\\game-start-6104.wav");
            switch(playerIds.size()) {
                case 1: 
                    pidOneLabel.setText(playerIds.get(0));
                    pidTextBox.setText("");
                    break;
                case 2: 
                    pidOneLabel.setText(playerIds.get(0));
                    pidTwoLabel.setText(playerIds.get(1));
                    pidTextBox.setText("");
                    break;
                case 3:
                    pidOneLabel.setText(playerIds.get(0));
                    pidTwoLabel.setText(playerIds.get(1));
                    pidThreeLabel.setText(playerIds.get(2));
                    pidTextBox.setText("");
                    break;
                case 4: 
                    pidOneLabel.setText(playerIds.get(0));
                    pidTwoLabel.setText(playerIds.get(1));
                    pidThreeLabel.setText(playerIds.get(2));
                    pidFourLabel.setText(playerIds.get(3));
                    pidTextBox.setText("");
                    break;
            }
            
            if(playerIds.size() == 5) {
                playerIds.remove(name);
                 JLabel message = new JLabel("Може бути тільки від 2 до 4 гравців!");
                message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
                JOptionPane.showMessageDialog(null, message);
                pidTextBox.setText("");
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        if(playerIds.size() == 1 || playerIds.size() == 0) {
             JLabel message = new JLabel("Повинно бути щонайменше 2 гравці!");
                message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
                JOptionPane.showMessageDialog(null, message);
                pidTextBox.setText("");
        }
        else {
            this.dispose();
            SoundManager.playSound("C:\\Users\\syndu\\Downloads\\game-start-6104.wav");
            new GameStage(playerIds).setVisible(true);
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void doneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButton1ActionPerformed

    private void doneButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButton2ActionPerformed

    private void doneButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButton3ActionPerformed

    private void doneButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButton4ActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        new Menu().setVisible(true);
        SoundManager.playSound("C:\\Users\\syndu\\Downloads\\game-start-6104.wav");
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void guideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideButtonActionPerformed
        new CardGuide().setVisible(true);
        SoundManager.playSound("C:\\Users\\syndu\\Downloads\\game-start-6104.wav");
        this.dispose();
    }//GEN-LAST:event_guideButtonActionPerformed

    private void returnButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseEntered
        returnButton.setLocation(80, returnButton.getY());
    }//GEN-LAST:event_returnButtonMouseEntered

    private void returnButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseExited
        returnButton.setLocation(90, returnButton.getY());
    }//GEN-LAST:event_returnButtonMouseExited

    private void guideButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guideButtonMouseEntered
       guideButton.setLocation(80, guideButton.getY());
    }//GEN-LAST:event_guideButtonMouseEntered

    private void guideButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guideButtonMouseExited
       guideButton.setLocation(90, guideButton.getY());
    }//GEN-LAST:event_guideButtonMouseExited

    private void doneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseEntered
       doneButton.setLocation(doneButton.getX(), 457);
    }//GEN-LAST:event_doneButtonMouseEntered

    private void doneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseExited
         doneButton.setLocation(doneButton.getX(), 452);
    }//GEN-LAST:event_doneButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlayerNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JButton doneButton1;
    private javax.swing.JButton doneButton2;
    private javax.swing.JButton doneButton3;
    private javax.swing.JButton doneButton4;
    private javax.swing.JButton guideButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pidFourLabel;
    private javax.swing.JLabel pidOneLabel;
    private javax.swing.JTextField pidTextBox;
    private javax.swing.JLabel pidThreeLabel;
    private javax.swing.JLabel pidTwoLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
