/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author syndu
 */
public class PickColorFrame extends javax.swing.JFrame {

   private UnoCard.Color wildColor = null;
   Boolean allow = false;
   PopUp popUp;
    
    public PickColorFrame() {
        initComponents();
    }
    
    public PickColorFrame(PopUp pop) {
        initComponents();
        popUp = pop;
    }

    public UnoCard.Color chooseColor(UnoCard card) {
        if (card.getColor() == UnoCard.Color.Wild) {
            this.setVisible(true);
            this.setResizable(false);
        }
        return card.getColor();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        redButton.setContentAreaFilled(false);
        redButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                redButtonMouseEntered(evt);
            }
        });
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        getContentPane().add(redButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, 140));

        blueButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        blueButton.setContentAreaFilled(false);
        blueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blueButtonMouseEntered(evt);
            }
        });
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(blueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 140));

        yellowButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        yellowButton.setContentAreaFilled(false);
        yellowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yellowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yellowButtonMouseEntered(evt);
            }
        });
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yellowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 150, 140, 140));

        greenButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        greenButton.setContentAreaFilled(false);
        greenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                greenButtonMouseEntered(evt);
            }
        });
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(greenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\Dont_select.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     
    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        wildColor = UnoCard.Color.Red;
        JLabel message = new JLabel("Було обрано червоний колір!");
        message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColor = UnoCard.Color.Red;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        ImageIcon icon = new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\Red_Wild.png");
        Image scaledImage = icon.getImage().getScaledInstance(89, 134, Image.SCALE_SMOOTH);
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon(scaledImage));
        popUp.game.setCardColor(UnoCard.Color.Red);
        popUp.dispose();
        SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
    }//GEN-LAST:event_redButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        wildColor = UnoCard.Color.Blue;
        JLabel message = new JLabel("Було обрано синій колір!");
        message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColor = UnoCard.Color.Blue;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        ImageIcon icon = new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\Blue_Wild.png");
        Image scaledImage = icon.getImage().getScaledInstance(89, 134, Image.SCALE_SMOOTH);
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon(scaledImage));
        popUp.game.setCardColor(UnoCard.Color.Blue);
        popUp.dispose();
        SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
    }//GEN-LAST:event_blueButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        wildColor = UnoCard.Color.Yellow;
        JLabel message = new JLabel("Було обрано жовтий колір!");
        message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColor = UnoCard.Color.Yellow;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        ImageIcon icon = new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\Yellow_Wild.png");
        Image scaledImage = icon.getImage().getScaledInstance(89, 134, Image.SCALE_SMOOTH);
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon(scaledImage));
        popUp.game.setCardColor(UnoCard.Color.Yellow);
        popUp.dispose();
        SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
    }//GEN-LAST:event_yellowButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        wildColor = UnoCard.Color.Green;
        JLabel message = new JLabel("Було обрано зелений колір!");
        message.setFont(new Font("Comic Sans MS", java.awt.Font.PLAIN, 14));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColor = UnoCard.Color.Green;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        ImageIcon icon = new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\Green_Wild.png");
        Image scaledImage = icon.getImage().getScaledInstance(89, 134, Image.SCALE_SMOOTH);
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon(scaledImage));
        popUp.game.setCardColor(UnoCard.Color.Green);
        popUp.dispose();
        SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
    }//GEN-LAST:event_greenButtonActionPerformed

    private void blueButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueButtonMouseEntered
     ImageIcon newImage = new ImageIcon("C:\\Users\\syndu\\Desktop\\selected_blue.png");
     SoundManager.playSound("C:\\Users\\syndu\\Downloads\\pop.wav");
     jLabel2.setIcon(newImage);
    }//GEN-LAST:event_blueButtonMouseEntered

    private void redButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redButtonMouseEntered
          ImageIcon newImage = new ImageIcon("C:\\Users\\syndu\\Desktop\\selected_red.png");
            SoundManager.playSound("C:\\Users\\syndu\\Downloads\\pop.wav");
          jLabel2.setIcon(newImage);
    }//GEN-LAST:event_redButtonMouseEntered

    private void greenButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenButtonMouseEntered
         ImageIcon newImage = new ImageIcon("C:\\Users\\syndu\\Desktop\\selected_green.png");
           SoundManager.playSound("C:\\Users\\syndu\\Downloads\\pop.wav");
     jLabel2.setIcon(newImage);
    }//GEN-LAST:event_greenButtonMouseEntered

    private void yellowButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowButtonMouseEntered
     ImageIcon newImage = new ImageIcon("C:\\Users\\syndu\\Desktop\\selected_yellow.png");
       SoundManager.playSound("C:\\Users\\syndu\\Downloads\\pop.wav");
     jLabel2.setIcon(newImage);
    }//GEN-LAST:event_yellowButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickColorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables
}
