/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import java.awt.Image;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author syndu
 */
public class PopUp extends javax.swing.JFrame {

   String cardImage ="";
   Game game;
   
   ArrayList<UnoCard> playerHand;
   int choice;
   ArrayList<JButton> cardButtons;
   GameStage gameStage;
   JButton topCardButton;
   UnoCard.Color declaredColor;
   
   public PopUp() {}
    public PopUp(String cardName, Game game, int index, ArrayList<JButton> cardButtons, GameStage gameStage, JButton topCardButton) {
        initComponents();
        cardImage = cardName;
        this.game = game;
        playerHand = game.getPlayerHand(game.getCurrentPlayer());
        choice = index;
        this.cardButtons = cardButtons;
        ImageIcon icon = new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\images\\Cards\\" + cardImage + ".png");
         Image scaledImage = icon.getImage().getScaledInstance(120, 170, Image.SCALE_SMOOTH);
        cardLabel.setIcon(new javax.swing.ImageIcon(scaledImage));
        
        this.gameStage = gameStage;
        this.topCardButton = topCardButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        useCardButton = new javax.swing.JButton();
        cardLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Скасувати");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 100, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Зіграти");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, 40));

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\слоти.png")); // NOI18N
        cancelButton.setBorder(null);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 100, 50));

        useCardButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        useCardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\слоти.png")); // NOI18N
        useCardButton.setBorder(null);
        useCardButton.setContentAreaFilled(false);
        useCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        useCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useCardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(useCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        cardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 190, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\PopUp_Window.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void useCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useCardButtonActionPerformed
     PickColorFrame pickColor = new PickColorFrame(this);
     SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
    declaredColor = pickColor.chooseColor(playerHand.get(choice));
    
    if (declaredColor != null) {
        try {
            // Спроба зіграти карту
            game.submitPlayerCard(game.getCurrentPlayer(), playerHand.get(choice), declaredColor);

            // Якщо хід успішний, оновлюємо інтерфейс
            if (declaredColor != UnoCard.Color.Wild) {
                gameStage.setPidName(game.getCurrentPlayer());
                gameStage.setButtonIcons();

                // Оновлення верхньої карти
                ImageIcon icon = new javax.swing.ImageIcon("C:\\Users\\syndu\\Desktop\\images\\Cards\\" + game.getTopCardImage());
                Image scaledImage = icon.getImage().getScaledInstance(89, 134, Image.SCALE_SMOOTH);
                topCardButton.setIcon(new javax.swing.ImageIcon(scaledImage));
                
                 SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
            }
        } catch (InvalidColorSubmissionException ex) {
            // Обробка недійсного кольору
            Logger.getLogger(PopUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidValueSubmissionException ex) {
            // Обробка недійсного значення
            Logger.getLogger(PopUp.class.getName()).log(Level.SEVERE, null, ex);
            showErrorDialog("Ця карта не може бути зіграна!");
        } catch (InvalidPlayerTurnException ex) {
            // Обробка невірного ходу гравця
            Logger.getLogger(PopUp.class.getName()).log(Level.SEVERE, null, ex);
            showErrorDialog("Це не ваш хід!");
        }
         this.dispose();
    }
    }//GEN-LAST:event_useCardButtonActionPerformed

    private void showErrorDialog(String message) {
    javax.swing.JOptionPane.showMessageDialog(this, message, "Помилка", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       this.dispose();
      SoundManager.playSound("C:\\Users\\syndu\\Downloads\\swoosh.wav");
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cardLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton useCardButton;
    // End of variables declaration//GEN-END:variables
}
